### ISSUE TITLE
Failing Tests on Backend

### ISSUE THREAD

**Issue by TedTimbrell** [EECS-393-Team/worldview#5]
`(. venv/bin/activate; \
	coverage run venv/bin/pytest; \
	coverage report -m --fail-under 100 --omit=venv/*;\
)
============================================================================= test session starts ==============================================================================
platform linux -- Python 3.6.6, pytest-4.0.0, py-1.7.0, pluggy-0.8.0
rootdir: /home/ted/Dev/worldview, inifile:
collected 1 item / 8 errors                                                                                                                                                    

==================================================================================== ERRORS ====================================================================================
_____________________________________________ ERROR collecting angular-worldview/node_modules/blocking-proxy/examples/e2e_test.py ______________________________________________
venv/lib/python3.6/site-packages/_pytest/python.py:450: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
venv/lib/python3.6/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
E     File "/home/ted/Dev/worldview/angular-worldview/node_modules/blocking-proxy/examples/e2e_test.py", line 8
E       print "Loading angularjs.org"
E                                   ^
E   SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Loading angularjs.org")?
_________________________________________ ERROR collecting angular-worldview/node_modules/node-gyp/gyp/pylib/gyp/MSVSSettings_test.py __________________________________________
venv/lib/python3.6/site-packages/_pytest/python.py:450: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
venv/lib/python3.6/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
E     File "/home/ted/Dev/worldview/angular-worldview/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 37
E       print '%s:%s:%d:%s %s' % (mode.upper(), os.path.basename(ctx[0]),
E                            ^
E   SyntaxError: invalid syntax
____________________________________________ ERROR collecting angular-worldview/node_modules/node-gyp/gyp/pylib/gyp/common_test.py _____________________________________________
venv/lib/python3.6/site-packages/_pytest/python.py:450: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
venv/lib/python3.6/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
E     File "/home/ted/Dev/worldview/angular-worldview/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 37
E       print '%s:%s:%d:%s %s' % (mode.upper(), os.path.basename(ctx[0]),
E                            ^
E   SyntaxError: invalid syntax
___________________________________________ ERROR collecting angular-worldview/node_modules/node-gyp/gyp/pylib/gyp/easy_xml_test.py ____________________________________________
venv/lib/python3.6/site-packages/_pytest/python.py:450: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
venv/lib/python3.6/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
E     File "/home/ted/Dev/worldview/angular-worldview/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 37
E       print '%s:%s:%d:%s %s' % (mode.upper(), os.path.basename(ctx[0]),
E                            ^
E   SyntaxError: invalid syntax
_____________________________________________ ERROR collecting angular-worldview/node_modules/node-gyp/gyp/pylib/gyp/input_test.py _____________________________________________
venv/lib/python3.6/site-packages/_pytest/python.py:450: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
venv/lib/python3.6/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
E     File "/home/ted/Dev/worldview/angular-worldview/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 37
E       print '%s:%s:%d:%s %s' % (mode.upper(), os.path.basename(ctx[0]),
E                            ^
E   SyntaxError: invalid syntax
________________________________________ ERROR collecting angular-worldview/node_modules/node-gyp/gyp/pylib/gyp/generator/msvs_test.py _________________________________________
venv/lib/python3.6/site-packages/_pytest/python.py:450: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
venv/lib/python3.6/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
E     File "/home/ted/Dev/worldview/angular-worldview/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 37
E       print '%s:%s:%d:%s %s' % (mode.upper(), os.path.basename(ctx[0]),
E                            ^
E   SyntaxError: invalid syntax
________________________________________ ERROR collecting angular-worldview/node_modules/node-gyp/gyp/pylib/gyp/generator/ninja_test.py ________________________________________
venv/lib/python3.6/site-packages/_pytest/python.py:450: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
venv/lib/python3.6/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
E     File "/home/ted/Dev/worldview/angular-worldview/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 37
E       print '%s:%s:%d:%s %s' % (mode.upper(), os.path.basename(ctx[0]),
E                            ^
E   SyntaxError: invalid syntax
________________________________________ ERROR collecting angular-worldview/node_modules/node-gyp/gyp/pylib/gyp/generator/xcode_test.py ________________________________________
venv/lib/python3.6/site-packages/_pytest/python.py:450: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
venv/lib/python3.6/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
E     File "/home/ted/Dev/worldview/angular-worldview/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 37
E       print '%s:%s:%d:%s %s' % (mode.upper(), os.path.basename(ctx[0]),
E                            ^
E   SyntaxError: invalid syntax
`

These 8 error are appearing currently in the backend when running `make test`.

**Comment by robert-wagner** [comment]
Fixed with makefile change
